### ISSUE TITLE
German ARD teletext not being extracted

### ISSUE THREAD

**Issue by craftbyte** [orryverducci/TtxFromTS#3] opened 2023-09-08 00:33 UTC
**Description**

While trying to extract teletext from the German ARD channel (which displays in VLC), I noticed that teletext extraction does not work with TtxFromTS.

**Steps To Reproduce**

1. Download [ard.zip](https://github.com/orryverducci/TtxFromTS/files/12554381/ard.zip) and extract the TS file
2. Run `TtxFromTS -i ard.ts --sid 1 --type t42 test.ts`
3. Output says: 

```
 TtxFromTS 2.0

[INFO] Found PMT PID for the service: 50
[INFO] Found teletext elementary stream PID: 3000
[INFO] Reading TS file: 10%
[INFO] Reading TS file: 20%
[INFO] Reading TS file: 30%
[INFO] Reading TS file: 40%
[INFO] Reading TS file: 50%
[INFO] Reading TS file: 60%
[INFO] Reading TS file: 70%
[INFO] Reading TS file: 80%
[INFO] Reading TS file: 90%
[INFO] Reading TS file: 100%

[STATISTICS]
Total number of packets: 56273
Packets processed: 5903
Teletext packets written: 0
```

**Expected Behavior**

Teletext gets extracted

**Additional Information**

All other German channels seem to work fine.

**Comment by orryverducci** [comment] 2023-09-09 16:46
Hi @craftbyte.

Thanks for the sample.

The issue is that Telekom Slovenije has incorrectly marked all the teletext packets as being subtitles, which are skipped by default. If you add `--include-subs` to the command it exports the T42 file as expected.

As this is an issue with the transport stream and not a software bug I'm closing this. However I've made a note that the command line output should probably be changed to say why packets are being skipped.

**Closed as completed by orryverducci** 2023-09-09 16:46 UTC
Labels: bug

**Comment by craftbyte** [comment] 2023-09-09 16:49
Ah, thanks for the info. I don't think it's Telekom, but the upstream ARD stream (this was just captured on the Telekom IPTV service). Yes, maybe just making it say "Extracted X/X Valid Teletext Packets" or something like that would be nice. I have sent an email to ARD now.

**Comment by orryverducci** [comment] 2023-09-09 16:55
I suspected Telekom as Das Erste has previously been ok. Plus the service is standard definition but it has the HD bug on screen. So it looks like they're taking Das Erste HD and transcoding it, which is where I'm guess the issue would be.

However it's been a while since I've checked Das Erste HD, so it could be ARD with the issue.

**Comment by craftbyte** [comment] 2023-09-09 17:57
The main reason I suspect ARD is that other down-scaled channels have normal teletext. Thanks for the suggestion though, I will also check with Telekom.
